name: libtester ci
on:
  push: 
    branches:
      - master
      - v*
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: ${{ github.workspace }}/essentials.sh
    - run: ${{ github.workspace }}/build.sh
    - run: ${{ github.workspace }}/remove.sh
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: ${{ github.workspace }}/essentials.sh
    - run: ${{ github.workspace }}/build.sh
    - run: make test
    - run: ${{ github.workspace }}/remove.sh