name: libtester ci
on:
  push: 
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: apt update && apt install git gcc make python3-dev libtool-bin libconfig-dev libc6-dev -y
    - run: ./build.sh
    - run: make uninstall && remove.sh
  test:
    runs-on: ubuntu-latest
    steps:
    - run: apt update && apt install git gcc make python3-dev libtool-bin libconfig-dev libc6-dev -y
    - run: ./build.sh
    - run: make test
    - run: make uninstall && remove.sh